server:
  port: 5555
  
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      
      - id: auth-service
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/auth_service/**
        
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user_service/**
        filters:
        - AuthenticationFilter
        
      - id: project-service
        uri: lb://PROJECT-SERVICE
        predicates:
        - Path=/project_service/**
        filters:
        - AuthenticationFilter
        
#      - id: login_api
#        uri: lb://USER-SERVICE
#        predicates:
#        - Path=/user_service/login
#        
#      - id: register_api
#        uri: lb://USER-SERVICE
#        predicates:
#        - Path=/user_service/register
#        
#      - id: get_user_api
#        uri: lb://USER-SERVICE
#        predicates:
#        - Path=/user_service/get/{userId}
#        filters:
#        - AuthenticationFilter

      
        
#        metadata:
#          cors: 
#            allowedOrigins: '*'
#            allowedHeaders: '*'
#            maxAge: 30
          
  main:
    web-application-type: reactive
